//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch n01.rc
//
#define IDS_STRING_TITLE                100
#define IDR_ACCELERATOR                 101
#define IDS_STRING_EXIT                 101
#define IDI_ICON_MAIN                   102
#define IDS_STRING_MENU_NOTHING         102
#define IDS_STRING_PLAYER1              103
#define IDS_STRING_PLAYER2              104
#define IDS_STRING_SAVE_TITLE           105
#define IDD_DIALOG_MIDDLE               106
#define IDS_STRING_TITLE_LEG            106
#define IDR_MENU_MAIN                   107
#define IDS_STRING_TITLE_LEG_BEST_OF    107
#define IDD_DIALOG_GAME_OPTION          108
#define IDS_STRING_SET_END              108
#define IDS_STRING_COM                  109
#define IDD_DIALOG_SET_KEY              110
#define IDS_STRING_COM_NAME             110
#define IDS_STRING_SCHEDULE_MODE        111
#define IDR_TEXT_ARRANGE                112
#define IDS_STRING_MENU_TOOL            112
#define IDD_DIALOG_ARRANGE              113
#define IDD_DIALOG_COM                  114
#define IDD_DIALOG_GAME_SCHEDULE        119
#define IDD_DIALOG_OPTION_KEY           120
#define IDD_DIALOG_OPTION_VIEW          121
#define IDD_DIALOG_GAME_HISTORY         122
#define IDD_DIALOG_SCORE_LIST           123
#define IDD_DIALOG_OPTION_PLAYER        124
#define IDD_DIALOG_FINISH               125
#define IDR_TEXT_ARRANGE_COM            128
#define IDD_DIALOG_CHECK_OUT            129
#define IDD_DIALOG_OPTION_PLUGIN        130
#define IDD_DIALOG_SET_PLUGIN           131
#define IDD_DIALOG_SET_PLUGIN_KEY       132
#define IDS_STRING_DEFAULT_FONT         150
#define IDS_STRING_ARRANGE_FONT         151
#define IDS_STRING_SCORED               200
#define IDS_STRING_TO_GO                201
#define IDS_STRING_ROUND                202
#define IDS_STRING_DARTS                203
#define IDS_STRING_FIRST_MARK           204
#define IDS_STRING_FINISH               250
#define IDS_STRING_SCORE_SWAP           251
#define IDS_STRING_SCORE_CLEAR          252
#define IDS_STRING_TIE                  253
#define IDS_STRING_GAME_STOP            254
#define IDS_STRING_MIDDLE               255
#define IDS_STRING_CHECK_OUT_MODE       256
#define IDS_STRING_AUTO_SAVE_MODE       257
#define IDS_STRING_PREV_LEG             258
#define IDS_STRING_P_FIRST              300
#define IDS_STRING_P_TOTAL              301
#define IDS_STRING_P_SETS               302
#define IDS_STRING_P_LEGS               303
#define IDS_STRING_P_TONS               304
#define IDS_STRING_P_100                305
#define IDS_STRING_P_140                307
#define IDS_STRING_P_180S               308
#define IDS_STRING_P_HIGHOFF            309
#define IDS_STRING_P_SHORT              310
#define IDS_STRING_P_AVERAGE            311
#define IDS_STRING_P_AVG_SCORE          312
#define IDS_STRING_P_AVG_DARTS          313
#define IDS_STRING_P_AVG_CHECK_OUT      314
#define IDS_STRING_P_AVG_CHECK_OUT_LARGE 315
#define IDS_STRING_P_ARRANGE            316
#define IDS_STRING_P_SEPARATE           317
#define IDS_STRING_P_COUNTS             318
#define IDS_STRING_P_WIN_DARTS          319
#define IDS_STRING_P_DOUBLE             320
#define IDS_STRING_P_LONG               321
#define IDS_STRING_P_AVG_FIRST9         322
#define IDS_STRING_P_AVG_FIRST9_SCORE   323
#define IDS_STRING_P_FIRST9_SCORE       323
#define IDS_STRING_P_AVG_FIRST9_DARTS   324
#define IDS_STRING_P_FIRST9_DARTS       324
#define IDS_STRING_P_AVG_KEEP           325
#define IDS_STRING_P_AVG_BREAK          326
#define IDS_STRING_P_AVG_KEEP_WON       327
#define IDS_STRING_P_AVG_KEEP_ALL       328
#define IDS_STRING_P_AVG_BREAK_WON      329
#define IDS_STRING_P_AVG_BREAK_ALL      330
#define IDS_STRING_P_FINISH_STATS       331
#define IDS_STRING_P_2_80_SUCCESS       332
#define IDS_STRING_P_2_80_FAILURE       333
#define IDS_STRING_P_81_130_SUCCESS     334
#define IDS_STRING_P_81_130_FAILURE     335
#define IDS_STRING_P_131_SUCCESS        336
#define IDS_STRING_P_131_FAILURE        337
#define IDS_STRING_OP_GAME_SAVE         400
#define IDS_STRING_OP_NAME              401
#define IDS_STRING_OP_LEVEL_TITLE       402
#define IDS_STRING_OP_LEVEL             403
#define IDS_STRING_OP_KEY_ACTION        500
#define IDS_STRING_OP_KEY_KEY           501
#define IDS_STRING_OP_DELETE            503
#define IDS_STRING_OP_KEY_NUMBER        504
#define IDS_STRING_OP_KEY_NUMBER_ERROR  505
#define IDS_STRING_OP_KEY_NOTHING       506
#define IDS_STRING_OP_PLUGIN_TITLE      510
#define IDS_STRING_OP_PLUGIN_DLL        511
#define IDS_STRING_OP_PLUGIN_FUNCTION   512
#define IDS_STRING_OP_PLUGIN_NO_PROP    513
#define IDS_STRING_OP_FILESELECT        514
#define IDS_STRING_OP_LIST_SET          600
#define IDS_STRING_OP_LIST_LEG          601
#define IDS_STRING_OP_LIST_DARTS        602
#define IDS_STRING_OP_LIST_PLAYER_INFO  603
#define IDS_STRING_OP_LIST_CLEAR        604
#define IDS_STRING_POS_BACKGROUND       700
#define IDS_STRING_POS_ODD_BACKGROUND   701
#define IDS_STRING_POS_SCORED_TEXT      702
#define IDS_STRING_POS_TOGO_TEXT        703
#define IDS_STRING_POS_HEADER_BACKGROUND 704
#define IDS_STRING_POS_HEADER_TEXT      705
#define IDS_STRING_POS_LAST3NUMBER_TEXT 706
#define IDS_STRING_POS_LINE             707
#define IDS_STRING_POS_SEPARATE         708
#define IDS_STRING_POS_TON_CIRCLE       709
#define IDS_STRING_POS_INPUT_BACKGROUND 710
#define IDS_STRING_POS_INPUT_TEXT       711
#define IDS_STRING_POS_INPUT_SELECT_BACKGROUND 712
#define IDS_STRING_POS_INPUT_SELECT_TEXT 713
#define IDS_STRING_POS_LEFT_BACKGROUND  714
#define IDS_STRING_POS_LEFT_TEXT        715
#define IDS_STRING_POS_LEFT_ACTIVE_BORDER 716
#define IDS_STRING_POS_PLAYER_NAME_BACKGROUND 717
#define IDS_STRING_POS_PLAYER_NAME_TEXT 718
#define IDS_STRING_POS_PLAYER_BACKGROUND 719
#define IDS_STRING_POS_PLAYER_TEXT      720
#define IDS_STRING_POS_PLAYER_INFO_TITLE 721
#define IDS_STRING_POS_VIEW_SEPARATE    722
#define IDS_STRING_POS_GUIDE_BACKGROUND 723
#define IDS_STRING_POS_GUIDE_TEXT       724
#define IDS_STRING_POS_GUIDE_SELECT_BACKGROUND 725
#define IDS_STRING_POS_GUIDE_SELECT_TEXT 726
#define IDS_STRING_POS_GUIDE_BOX_BACKGROUND 727
#define IDS_STRING_POS_GUIDE_BOX_TEXT   728
#define IDS_STRING_POS_GUIDE_BOX_FRAME  729
#define IDS_STRING_POS_GUIDE_BOX_DISABLE 730
#define IDS_STRING_RESET_COLOR          740
#define IDS_STRING_OP_SCH_START_SCORE   900
#define IDS_STRING_OP_SCH_ROUND         901
#define IDS_STRING_OP_SCH_LEG           902
#define IDS_STRING_OP_SCH_P1            903
#define IDS_STRING_OP_SCH_P2            904
#define IDS_STRING_OP_SCH_BEST_OF       905
#define IDS_STRING_OP_SCH_OK            906
#define IDS_STRING_OP_SCH_TITLE         907
#define IDC_BUTTON_P1                   1000
#define IDC_BUTTON_P2                   1001
#define IDC_COMBO_P1_NAME               1001
#define IDC_COMBO_P2_NAME               1009
#define IDC_CHECK_P1_SCORE              1010
#define IDC_CHECK_P2_SCORE              1011
#define IDC_BUTTON_SAVE                 1012
#define IDC_LIST_KEY                    1014
#define IDC_BUTTON_UP                   1015
#define IDC_BUTTON_DOWN                 1016
#define IDC_RADIO_301                   1017
#define IDC_BUTTON_ADD                  1017
#define IDC_RADIO_501                   1018
#define IDC_BUTTON_EDIT                 1018
#define IDC_HOTKEY_KEY                  1018
#define IDC_BUTTON_DELETE               1019
#define IDC_COMBO_ACTION                1019
#define IDC_RADIO_1001                  1020
#define IDC_EDIT_INPUT                  1020
#define IDC_COMBO_LEG                   1021
#define IDC_VIEW_SCORE                  1022
#define IDC_STATIC_P1                   1023
#define IDC_STATIC_P2                   1024
#define IDC_EDIT_LEFT                   1026
#define IDC_CHECK_COM2                  1028
#define IDC_COMBO_COM2                  1029
#define IDC_STATIC_THROW_1              1030
#define IDC_CHECK_COM1                  1030
#define IDC_STATIC_THROW_2              1031
#define IDC_COMBO_COM1                  1031
#define IDC_STATIC_THROW_3              1032
#define IDC_SPIN_LEFT                   1033
#define IDC_TREE_ARRANGE                1036
#define IDC_CHECK_ROUND_LIMIT           1037
#define IDC_COMBO_COLOR                 1038
#define IDC_BUTTON_COLOR                1039
#define IDC_STATIC_FRAME                1041
#define IDC_BUTTON_RESET                1042
#define IDC_COMBO_FONT                  1045
#define IDC_EDIT_SCORE                  1049
#define IDC_RADIO_ETC                   1050
#define IDC_EDIT_ROUND                  1051
#define IDC_EDIT_P1_SCORE               1052
#define IDC_EDIT_P2_SCORE               1053
#define IDC_EDIT_LEG                    1054
#define IDC_CHECK_BEST_OF               1057
#define IDC_LIST_SCORE_LIST             1059
#define IDC_VIEW_P1                     1060
#define IDC_VIEW_P2                     1061
#define IDC_BUTTON_VIEW                 1061
#define IDC_BUTTON_CLEAR                1062
#define IDC_LIST_GAME                   1062
#define IDC_CHECK_LEG_LIMIT             1071
#define IDC_STATIC_LEG                  1072
#define IDC_CHECK_SETS                  1074
#define IDC_CHECK_LEGS                  1075
#define IDC_CHECK_TONS                  1076
#define IDC_CHECK_180S                  1077
#define IDC_CHECK_HIGH_OFF              1078
#define IDC_CHECK_SHORT                 1079
#define IDC_CHECK_AVG_SCORE             1080
#define IDC_CHECK_AVG_DARTS             1081
#define IDC_CHECK_NAME                  1082
#define IDC_CHECK_FIRST                 1083
#define IDC_CHECK_ARRANGE               1084
#define IDC_CHECK_AVG_CHECK_OUT         1085
#define IDC_BUTTON_FINISH_1             1086
#define IDC_CHECK_AVG_CHECK_OUT_COUNT   1086
#define IDC_EDIT_COUNT                  1087
#define IDC_CHECK_LONG                  1087
#define IDC_BUTTON_FINISH_2             1088
#define IDC_SPIN_COUNT                  1088
#define IDC_CHECK_AVG_KEEP              1088
#define IDC_BUTTON_FINISH_3             1089
#define IDC_CHECK_AVG_FIRST9            1089
#define IDC_CHECK_LARGE_FONT            1090
#define IDC_CHECK_AVG_KEEP_COUNT        1091
#define IDC_CHECK_140                   1092
#define IDC_CHECK_AVG_BREAK             1093
#define IDC_CHECK_100                   1094
#define IDC_CHECK_AVG_BREAK_COUNT       1095
#define IDC_SPIN_INPUT                  1096
#define IDC_CHECK_AVG_PPR               1096
#define IDC_SPIN_SCORE                  1097
#define IDC_SPIN_ROUND                  1098
#define IDC_SPIN_LEG                    1099
#define IDC_SPIN_P1_SCORE               1100
#define IDC_LIST_PLUGIN                 1100
#define IDC_SPIN_P2_SCORE               1101
#define IDC_LIST                        1102
#define IDC_BUTTON_PROPERTY             1104
#define IDC_CHECK_CHANGE_FIRST          1105
#define IDC_BUTTON_KEY                  1106
#define ID_ACCEL_ESC                    40002
#define ID_ACCEL_NONE                   40003
#define ID_ACCEL_UP                     40006
#define ID_ACCEL_DOWN                   40007
#define ID_ACCEL_TAB                    40008
#define ID_ACCEL_STAB                   40009
#define ID_ACCEL_PRIOR                  40011
#define ID_ACCEL_NEXT                   40012
#define ID_MENUITEM_SHOW_LEFT           40013
#define ID_MENUITEM_SHOW_PLAYER         40014
#define ID_MENUITEM_SHOW_DARTSCOUNT     40015
#define ID_MENUITEM_NEW_GAME            40016
#define ID_MENUITEM_EXIT                40017
#define ID_MENUITEM_FINISH_ONE          40018
#define ID_MENUITEM_FINISH_TWO          40019
#define ID_MENUITEM_FINISH_THREE        40020
#define ID_MENUITEM_MIDDLE              40021
#define ID_ACCEL_HOME                   40022
#define ID_ACCEL_END                    40023
#define ID_MENUITEM_ABOUT               40024
#define ID_MENUITEM_SCORE_LEFT          40026
#define ID_MENUITEM_SCORE_SWAP          40027
#define ID_MENUITEM_NOTHING             40028
#define ID_MENUITEM_SHOW_GUIDE          40031
#define ID_MENUITEM_SCORE_CLEAR         40033
#define ID_MENUITEM_ARRANGE             40034
#define ID_MENUITEM_GAME_HISTORY        40038
#define ID_MENUITEM_AUTO_SAVE           40039
#define ID_MENUITEM_NEW_SCHEDULE        40040
#define ID_MENUITEM_OPTION              40041
#define ID_MENUITEM_SET_SCHEDULE        40042
#define ID_MENUITEM_CHECK_OUT_MODE      40043
#define ID_MENUITEM_PREV_LEG            40045
#define ID_MENUITEM_FONT_L              40046
#define ID_MENUITEM_FONT_M              40047
#define ID_MENUITEM_FONT_S              40048
#define ID_MENUITEM_SHOW_NAME           40049
#define IDS_STRING_LEFT                 40050
#define IDS_STRING_RIGHT                40051
#define ID_MENUITEM_FULL_SCREEN         40052
#define ID_MENUITEM_ONLINE              40053

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40054
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
